# Mkfile to build the various .md and .txt files

# {X}fm tools can be cloned and built using: https://github.com/ScottDaniels/xfm.git


all:V: README.md README.txt README.html README.ps

# tfm always insists on a leading space, so we must strip it as bloody markdown
# treats leading spaces as significant (grrr)
#
%.md:: %.xfm
	MARKDOWN=1 tfm $prereq stdout| sed 's/.//' >$target

%.txt:: %.xfm
	MARKDOWN=0 tfm $prereq $target

%.ps:: %.xfm
	MARKDOWN=0 pfm $prereq $target

%.html:: %.xfm
	MARKDOWN=0 hfm $prereq $target
